package model;

/**
 *
 * Constants for maze instructions
 *
 * @author Arthur Gastineau
 */

public class MazeInstructionConstants {

	/**
	 * The initial instruction displayed when the maze is generated.
	 */
	public static final String INIT = "Welcome to the Maze Solver! You can click on \"Generate\" to create a maze or \"Load\" to load one! Then click the \"Solve\" button to solve the maze.";

	/**
	 * The instruction displayed when the maze is solved.
	 */
	public static final String SOLVED = "Maze solved! You can modify it and see the shortest path in real time! Once you are done you can \"Load\" or \"Generate\" a new one";

	/**
	 * The instruction displayed when the custom maze is generated by the user.
	 */
	public static final String GENERATED = "Maze successfully generated! You can edit the maze and save it with the \"Save\" button! Click the \"Solve\" button to solve the maze.";

	/**
	 * The instruction displayed when the maze is loaded by the user.
	 */
	public static final String LOADED = "Maze successfully loaded! You can modify it if you desire! Click the \"Solve\" button to solve the maze.";
}
